import {runEngine,num,arr,obj,clamp,sum,mean,weightedMean,stdev,median,quantile,zscore,slope,corr,ema,atr,rsi,vwap,pct,sigmoid,safeDiv,hash,round,candles,closes,highs,lows,volumes} from "./kernel.js";
export const MODULE=Object.freeze({"id":"TITAN-04","slug":"market-entry","title":"Market Entry","version":"3.0.0","modes":["LIVE","PAPER","BACKTEST","RESEARCH","AUDIT"],"inputs":["market","orderbook","trades","risk","microstructure"],"outputs":["entry","slippage","impact","cost","fillQuality"],"gates":["spread","depth","latency","cost"],"lifecycle":["OBSERVE","NORMALIZE","DERIVE","GATE","DECIDE","AUDIT"],"invariants":["no lookahead","deterministic","fail closed","traceable evidence"]});
function derive(input={}){
const m=input.market||{},ob=input.orderbook||m.orderBook||{},b=arr(ob.bids),a=arr(ob.asks),bb=num(b[0]?.[0]??b[0]?.price),aa=num(a[0]?.[0]??a[0]?.price),mid=bb!=null&&aa!=null?(bb+aa)/2:num(m.price),spread=bb!=null&&aa!=null?aa-bb:0;
const bd=sum(b.slice(0,10).map(x=>num(x?.[1]??x?.size,0))),ad=sum(a.slice(0,10).map(x=>num(x?.[1]??x?.size,0))),imb=safeDiv(bd-ad,bd+ad,0),qty=num(input.quantity??input.risk?.quantity,0),impact=safeDiv(qty,Math.max(1,input.direction==="LONG"?ad:bd),0)*spread;
const slippage=Math.abs(mid-num(m.price??mid))+Math.abs(impact),cost=slippage+spread*.5+num(input.fees,0),quality=clamp(1-safeDiv(cost,Math.max(mid*.001,.0001),0));
return{status:quality>.55?"READY":"DEGRADE",direction:input.direction||input.decision||"NO_TRADE",score:quality,confidence:quality,signals:["spread="+round(spread,6),"imb="+round(imb,3),"impact="+round(impact,6)],gates:{spread:spread<Math.max(mid*.0008,.01),depth:bd+ad>0,latency:num(input.latencyMs,100)<750,cost:quality>.5},metrics:{mid,spread,bd,ad,imb,impact,slippage,cost},entry:mid,slippage,impact,cost,fillQuality:quality};
}
export function evaluate(input={}){return runEngine({module:MODULE,input,derive})}
export function selfTest(){const t=1700000000000;const a=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t-1});const b=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t+1});return{module:MODULE.id,passed:a.provenance.lookaheadSafe&&b.diagnostics.errors.includes("LOOKAHEAD_VIOLATION")}}
export function explain(r){const x=r||evaluate({});return{module:MODULE.id,status:x.state?.status,direction:x.state?.direction,score:x.state?.score,confidence:x.state?.confidence,signals:x.state?.signals,gates:x.state?.gates,metrics:x.state?.metrics,blockers:x.state?.blockers,traceId:x.diagnostics?.traceId}}
export default evaluate;