import {runEngine,num,arr,obj,clamp,sum,mean,weightedMean,stdev,median,quantile,zscore,slope,corr,ema,atr,rsi,vwap,pct,sigmoid,safeDiv,hash,round,candles,closes,highs,lows,volumes} from "./kernel.js";
export const MODULE=Object.freeze({"id":"TITAN-09","slug":"probability-engine","title":"Probability Engine","version":"3.0.0","modes":["LIVE","PAPER","BACKTEST","RESEARCH","AUDIT"],"inputs":["ensemble","metaProbability","analog","calibration","features","setup","regime","eventRisk"],"outputs":["probability","uncertainty","direction","evidence"],"gates":["dataSufficiency","calibration","regime","conflict"],"lifecycle":["OBSERVE","NORMALIZE","DERIVE","GATE","DECIDE","AUDIT"],"invariants":["no lookahead","deterministic","fail closed","traceable evidence"]});
function derive(input={}){
const e=input.ensemble||{},a=input.analog||{},c=input.calibration||{},f=input.features?.["15m"]||input.features||{},s=input.setup||{},r=input.regime||input.regimes?.["15m"]||{},vals=[e.longProbability,e.probability,input.metaProbability,a.probability,c.probability].map(Number).filter(Number.isFinite);
const base=vals.length?mean(vals):.5,mom=f.rsi==null?.5:clamp(.5+(f.rsi-50)/100),sq=clamp(s.quality??.5),rb=r.trend==="UPTREND"?.62:r.trend==="DOWNTREND"?.38:.5,p=clamp(.4*base+.2*mom+.2*sq+.2*rb-(input.eventRisk?.riskLevel==="HIGH"?.1:0)),unc=clamp(.08+(stdev(vals)||.2)*.8+(vals.length<3?.1:0)),dir=p>.56?"LONG":p<.44?"SHORT":"NO_TRADE";
return{status:vals.length>=2?"READY":"LOW_EVIDENCE",direction:dir,score:Math.max(p,1-p),confidence:1-unc,signals:["p="+round(p,4),"unc="+round(unc,4)],gates:{dataSufficiency:vals.length>=2,calibration:c.ready!==false,regime:Boolean(r),conflict:(stdev(vals)||0)<.3},metrics:{vals,base,mom,sq,rb},probability:dir==="SHORT"?1-p:p,uncertainty:unc,evidence:{components:vals}};
}
export function evaluate(input={}){return runEngine({module:MODULE,input,derive})}
export function selfTest(){const t=1700000000000;const a=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t-1});const b=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t+1});return{module:MODULE.id,passed:a.provenance.lookaheadSafe&&b.diagnostics.errors.includes("LOOKAHEAD_VIOLATION")}}
export function explain(r){const x=r||evaluate({});return{module:MODULE.id,status:x.state?.status,direction:x.state?.direction,score:x.state?.score,confidence:x.state?.confidence,signals:x.state?.signals,gates:x.state?.gates,metrics:x.state?.metrics,blockers:x.state?.blockers,traceId:x.diagnostics?.traceId}}
export default evaluate;