import {runEngine,num,arr,obj,clamp,sum,mean,weightedMean,stdev,median,quantile,zscore,slope,corr,ema,atr,rsi,vwap,pct,sigmoid,safeDiv,hash,round,candles,closes,highs,lows,volumes} from "./kernel.js";
export const MODULE=Object.freeze({"id":"TITAN-11","slug":"calibration-engine","title":"Calibration Engine","version":"3.0.0","modes":["LIVE","PAPER","BACKTEST","RESEARCH","AUDIT"],"inputs":["predictions","outcomes","bins","latestProbability"],"outputs":["calibrated","ece","brier","isotonic"],"gates":["sampleSize","resolution","monotonicity","temporalSplit"],"lifecycle":["OBSERVE","NORMALIZE","DERIVE","GATE","DECIDE","AUDIT"],"invariants":["no lookahead","deterministic","fail closed","traceable evidence"]});
function derive(input={}){const preds=arr(input.predictions).map(Number),ys=arr(input.outcomes).map(Number),n=Math.min(preds.length,ys.length),rows=preds.slice(0,n).map((p,i)=>({p:clamp(p),y:ys[i]>0?1:0,timestamp:num(input.timestamps?.[i],i)}));rows.sort((a,b)=>a.timestamp-b.timestamp);const bins=Math.max(5,Math.min(20,Math.floor(num(input.bins,12)))),hist=Array.from({length:bins},()=>({n:0,sumP:0,sumY:0}));for(const r of rows){const i=Math.min(bins-1,Math.floor(r.p*bins));hist[i].n++;hist[i].sumP+=r.p;hist[i].sumY+=r.y}const non=hist.filter(x=>x.n),ece=non.reduce((s,b)=>s+b.n/Math.max(1,n)*Math.abs(b.sumP/b.n-b.sumY/b.n),0),brier=n?mean(rows.map(r=>(r.p-r.y)**2)):null,logLoss=n?-mean(rows.map(r=>r.y?Math.log(Math.max(r.p,.001)):Math.log(Math.max(1-r.p,.001)))):null;
const blocks=[];for(const b of non){const y=b.sumY/b.n,x=b.sumP/b.n;blocks.push({x,y,n:b.n})}const pav=[];for(const b of blocks){let z={...b};while(pav.length&&z.y<pav.at(-1).y){const a=pav.pop();z={x:(a.x*a.n+z.x*z.n)/(a.n+z.n),y:(a.y*a.n+z.y*z.n)/(a.n+z.n),n:a.n+z.n}}pav.push(z)}const predict=p=>{if(!pav.length)return p;const x=clamp(p);if(pav.length===1)return clamp(pav[0].y);if(x<=pav[0].x)return clamp(pav[0].y);if(x>=pav.at(-1).x)return clamp(pav.at(-1).y);for(let i=1;i<pav.length;i++){const a=pav[i-1],b=pav[i];if(x<=b.x){const w=safeDiv(x-a.x,b.x-a.x,0);return clamp(a.y+w*(b.y-a.y))}}return clamp(pav.at(-1).y)};
const latest=predict(input.latestProbability??.5),resolution=non.length,ready=n>=100&&resolution>=5,temporal=rows.every((r,i)=>i===0||r.timestamp>=rows[i-1].timestamp);
return{status:ready&&temporal?"READY":"WARMING",direction:latest>.55?"LONG":latest<.45?"SHORT":"NO_TRADE",score:latest,confidence:ready?clamp(1-ece):.25,signals:["n="+n,"ECE="+round(ece,5),"Brier="+round(brier??.25,5),"LogLoss="+round(logLoss??.69,5)],gates:{sampleSize:n>=100,resolution:resolution>=5,monotonicity:pav.every((q,i)=>i===0||q.y>=pav[i-1].y),temporalSplit:Boolean(input.temporalSplit),chronological:temporal},metrics:{n,ece,brier,logLoss,binsUsed:resolution},calibrated:ready&&temporal,ece,brier,logLoss,isotonic:pav,estimatedProbability:latest,predictor:"PAV_LINEAR_INTERPOLATION"};}
export function evaluate(input={}){return runEngine({module:MODULE,input,derive})}
export function selfTest(){const t=1700000000000;const a=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t-1});const b=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t+1});return{module:MODULE.id,passed:a.provenance.lookaheadSafe&&b.diagnostics.errors.includes("LOOKAHEAD_VIOLATION")}}
export function explain(r){const x=r||evaluate({});return{module:MODULE.id,status:x.state?.status,direction:x.state?.direction,score:x.state?.score,confidence:x.state?.confidence,signals:x.state?.signals,gates:x.state?.gates,metrics:x.state?.metrics,blockers:x.state?.blockers,traceId:x.diagnostics?.traceId}}
export default evaluate;