import {runEngine,num,arr,obj,clamp,sum,mean,weightedMean,stdev,median,quantile,zscore,slope,corr,ema,atr,rsi,vwap,pct,sigmoid,safeDiv,hash,round,candles,closes,highs,lows,volumes} from "./kernel.js";
export const MODULE=Object.freeze({"id":"TITAN-14","slug":"regime-engine","title":"Regime Engine","version":"3.0.0","modes":["LIVE","PAPER","BACKTEST","RESEARCH","AUDIT"],"inputs":["candles","atr","features","market"],"outputs":["trend","volatility","environment","state","compatibility"],"gates":["sample","stability","classification"],"lifecycle":["OBSERVE","NORMALIZE","DERIVE","GATE","DECIDE","AUDIT"],"invariants":["no lookahead","deterministic","fail closed","traceable evidence"]});
function derive(input={}){
const c=candles(input),x=closes(input),a=num(input.atr??atr(c)),e20=ema(x,20),e50=ema(x,50),e200=ema(x,200),s=slope(x.slice(-50)),ap=safeDiv(a,num(x.at(-1)),0);
const trend=s>.15*(a||1)?"UPTREND":s<-.15*(a||1)?"DOWNTREND":Math.abs((e20??0)-(e50??0))<(a||1)*.2?"RANGE":"TRANSITION",vol=ap>.012?"HIGH":ap<.004?"LOW":"NORMAL";
const env=vol==="HIGH"&&Math.abs(s)<(a||1)*.12?"SHOCK_RANGE":vol==="HIGH"?"EXPANSION":vol==="LOW"?"COMPRESSION":"NORMAL",state=trend==="RANGE"&&env==="COMPRESSION"?"MEAN_REVERSION":trend!=="RANGE"&&env!=="SHOCK_RANGE"?"TREND_FOLLOW":"TACTICAL";
return{status:c.length>=60?"READY":"LOW_SAMPLE",direction:trend==="UPTREND"?"LONG":trend==="DOWNTREND"?"SHORT":"NO_TRADE",score:clamp(.5+(trend==="UPTREND"?.2:trend==="DOWNTREND"?-.2:0)),confidence:clamp(.45+Math.abs(s)/Math.max(a,.0001)*.2),signals:[trend,vol,env,state],gates:{sample:c.length>=60,stability:true,classification:true},metrics:{a,ap,e20,e50,e200,s},trend,volatility:vol,environment:env,state,compatibility:{trendFollow:trend!=="RANGE"&&env!=="SHOCK_RANGE",breakout:env==="EXPANSION",reversion:state==="MEAN_REVERSION"}};
}
export function evaluate(input={}){return runEngine({module:MODULE,input,derive})}
export function selfTest(){const t=1700000000000;const a=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t-1});const b=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t+1});return{module:MODULE.id,passed:a.provenance.lookaheadSafe&&b.diagnostics.errors.includes("LOOKAHEAD_VIOLATION")}}
export function explain(r){const x=r||evaluate({});return{module:MODULE.id,status:x.state?.status,direction:x.state?.direction,score:x.state?.score,confidence:x.state?.confidence,signals:x.state?.signals,gates:x.state?.gates,metrics:x.state?.metrics,blockers:x.state?.blockers,traceId:x.diagnostics?.traceId}}
export default evaluate;