import {runEngine,num,arr,obj,clamp,sum,mean,weightedMean,stdev,median,quantile,zscore,slope,corr,ema,atr,rsi,vwap,pct,sigmoid,safeDiv,hash,round,candles,closes,highs,lows,volumes} from "./kernel.js";
export const MODULE=Object.freeze({"id":"TITAN-16","slug":"event-engine","title":"Event Engine","version":"3.0.0","modes":["LIVE","PAPER","BACKTEST","RESEARCH","AUDIT"],"inputs":["timestamp","events","fundingTime","nextFundingTime","externalEvents"],"outputs":["riskLevel","flags","tradeAllowed","windows"],"gates":["timestamp","eventFreshness","windowLogic"],"lifecycle":["OBSERVE","NORMALIZE","DERIVE","GATE","DECIDE","AUDIT"],"invariants":["no lookahead","deterministic","fail closed","traceable evidence"]});
function derive(input={}){
const now=num(input.timestamp,Date.now()),windows=[];for(const e of [...arr(input.events),...arr(input.externalEvents)]){const t=num(e.timestamp??e.ts??e.time);if(t!=null&&Math.abs(t-now)<45*60*1000)windows.push({type:e.type??e.name??"EVENT",deltaMs:t-now,severity:String(e.severity??"MEDIUM").toUpperCase()})}const f=num(input.nextFundingTime);if(f!=null&&Math.abs(f-now)<45*60*1000)windows.push({type:"FUNDING",deltaMs:f-now,severity:"MEDIUM"});
const high=windows.some(x=>x.severity==="HIGH"),riskLevel=high?"HIGH":windows.length>=2?"HIGH":windows.length?"MEDIUM":"LOW",allow=riskLevel!=="HIGH";
return{status:allow?"READY":"BLOCK",direction:"NO_TRADE",score:riskLevel==="LOW"?.85:riskLevel==="MEDIUM"?.6:.2,confidence:.9,signals:windows.map(x=>x.type),gates:{timestamp:Boolean(input.timestamp),eventFreshness:true,windowLogic:true},metrics:{count:windows.length,high},riskLevel,flags:windows.map(x=>x.type),tradeAllowed:allow,windows};
}
export function evaluate(input={}){return runEngine({module:MODULE,input,derive})}
export function selfTest(){const t=1700000000000;const a=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t-1});const b=evaluate({mode:"RESEARCH",timestamp:t,decisionTimestamp:t,sourceTimestamp:t+1});return{module:MODULE.id,passed:a.provenance.lookaheadSafe&&b.diagnostics.errors.includes("LOOKAHEAD_VIOLATION")}}
export function explain(r){const x=r||evaluate({});return{module:MODULE.id,status:x.state?.status,direction:x.state?.direction,score:x.state?.score,confidence:x.state?.confidence,signals:x.state?.signals,gates:x.state?.gates,metrics:x.state?.metrics,blockers:x.state?.blockers,traceId:x.diagnostics?.traceId}}
export default evaluate;