export const EPS=1e-12;
export const num=(v,d=null)=>{const x=Number(v);return Number.isFinite(x)?x:d};
export const arr=v=>Array.isArray(v)?v:[];
export const obj=v=>v&&typeof v==="object"?v:{};
export const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,num(v,a)));
export const sum=v=>arr(v).map(Number).filter(Number.isFinite).reduce((a,b)=>a+b,0);
export const mean=v=>{const a=arr(v).map(Number).filter(Number.isFinite);return a.length?sum(a)/a.length:null};
export const weightedMean=(v,w)=>{let s=0,z=0;for(let i=0;i<Math.min(arr(v).length,arr(w).length);i++){const x=num(v[i]),y=num(w[i]);if(x!=null&&y!=null&&y>0){s+=x*y;z+=y}}return z?s/z:null};
export const stdev=v=>{const a=arr(v).map(Number).filter(Number.isFinite),m=mean(a);return a.length>1?Math.sqrt(mean(a.map(x=>(x-m)**2))):0};
export const median=v=>{const a=arr(v).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
export const quantile=(v,q=.5)=>{const a=arr(v).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const p=clamp(q)*(a.length-1),i=Math.floor(p),j=Math.ceil(p);return a[i]+(a[j]-a[i])*(p-i)};
export const zscore=(x,v)=>{const m=mean(v),s=stdev(v),n=num(x);return m==null||s<EPS||n==null?0:(n-m)/s};
export const slope=v=>{const a=arr(v).map(Number).filter(Number.isFinite);if(a.length<2)return 0;const n=a.length,x=(n-1)/2,y=mean(a);let p=0,q=0;for(let i=0;i<n;i++){p+=(i-x)*(a[i]-y);q+=(i-x)**2}return q?p/q:0};
export const corr=(a,b)=>{const n=Math.min(arr(a).length,arr(b).length);if(n<3)return 0;const x=arr(a).slice(-n).map(Number),y=arr(b).slice(-n).map(Number),mx=mean(x),my=mean(y);let p=0,xx=0,yy=0;for(let i=0;i<n;i++){const u=x[i]-mx,v=y[i]-my;p+=u*v;xx+=u*u;yy+=v*v}return xx&&yy?p/Math.sqrt(xx*yy):0};
export const ema=(v,p=20)=>{const a=arr(v).map(Number),k=2/(p+1);let e=null;for(const x of a)if(Number.isFinite(x))e=e==null?x:x*k+e*(1-k);return e};
export const atr=(cs,p=14)=>{const a=arr(cs),t=[];for(let i=0;i<a.length;i++){const h=num(a[i]?.high),l=num(a[i]?.low),pc=i?num(a[i-1]?.close):null;if(h==null||l==null)continue;t.push(pc==null?h-l:Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)))}return mean(t.slice(-p))};
export const rsi=(v,p=14)=>{const a=arr(v).map(Number),g=[],l=[];for(let i=1;i<a.length;i++){const d=a[i]-a[i-1];g.push(Math.max(0,d));l.push(Math.max(0,-d))}const ag=mean(g.slice(-p)),al=mean(l.slice(-p));return al==null?null:al<EPS?100:100-100/(1+ag/al)};
export const vwap=cs=>{let pv=0,q=0;for(const c of arr(cs)){const h=num(c?.high),l=num(c?.low),cl=num(c?.close),v=num(c?.volume,0);if(h==null||l==null||cl==null)continue;pv+=(h+l+cl)/3*v;q+=v}return q?pv/q:null};
export const pct=(a,b)=>{const x=num(a),y=num(b);return x==null||y==null||Math.abs(y)<EPS?null:(x-y)/y};
export const sigmoid=x=>1/(1+Math.exp(-Math.max(-40,Math.min(40,num(x,0)))));
export const safeDiv=(a,b,d=null)=>{const x=num(a),y=num(b);return x!=null&&y!=null&&Math.abs(y)>EPS?x/y:d};
export const hash=x=>{const s=JSON.stringify(x??null);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)};
export const round=(x,d=6)=>{const n=num(x);if(n==null)return null;const p=10**d;return Math.round(n*p)/p};
export const candles=i=>arr(i?.candles??i?.candles15m??i?.data?.candles);
export const closes=i=>candles(i).map(x=>num(x?.close)).filter(x=>x!=null);
export const highs=i=>candles(i).map(x=>num(x?.high)).filter(x=>x!=null);
export const lows=i=>candles(i).map(x=>num(x?.low)).filter(x=>x!=null);
export const volumes=i=>candles(i).map(x=>num(x?.volume)).filter(x=>x!=null);
export function runEngine({module,input={},derive}){const errors=[],warnings=[],missing=[];const d=num(input.decisionTimestamp??input.timestamp);if(num(input.sourceTimestamp)!=null&&d!=null&&num(input.sourceTimestamp)>d)errors.push("LOOKAHEAD_VIOLATION");for(const k of ["candles","candles15m","candles1m","candles5m","candles1h","candles4h","candles1d"]){for(const x of arr(input[k])){const t=num(x?.timestamp??x?.ts??x?.time);if(t!=null&&d!=null&&t>d)errors.push("LOOKAHEAD_VIOLATION")}}for(const k of arr(module.inputs)){const v=input[k];if(v==null)missing.push(k)}if(missing.length)warnings.push("MISSING_INPUTS:"+missing.join(","));let r={status:"BLOCKED",direction:"NO_TRADE",score:.5,confidence:0,signals:[],gates:{},metrics:{}};if(!errors.length){try{r=derive(input)||r}catch(e){errors.push("ENGINE_EXCEPTION");warnings.push(String(e?.message||e))}}const state={status:errors.length?"BLOCKED":r.status??"READY",direction:r.direction??"NO_TRADE",score:clamp(r.score),confidence:clamp(r.confidence,0,1),signals:arr(r.signals),gates:obj(r.gates),metrics:obj(r.metrics),blockers:[...new Set([...errors,...warnings])]};return{module,state,result:r,provenance:{lookaheadSafe:!errors.includes("LOOKAHEAD_VIOLATION"),sourceTimestamp:num(input.sourceTimestamp),decisionTimestamp:d,inputHash:hash(input)},diagnostics:{errors:[...new Set(errors)],warnings:[...new Set(warnings)],traceId:module.id+":"+hash({state,source:input.sourceTimestamp})},contract:{inputs:module.inputs,outputs:module.outputs,gates:module.gates}}}
