const BASE = process.env.BYBIT_BASE_URL || 'https://api.bybit.com';
const SYMBOL='ETHUSDT';
const INTERVALS=['1','5','15','60','240','D'];
const PERIODS=['5min','15min','30min','1h','4h','1d'];
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
async function request(path,params={},signal){const u=new URL(BASE+path);for(const [k,v] of Object.entries(params))if(v!=null)u.searchParams.set(k,String(v));const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'SCALP-Omega-Bybit-Adapter/3.0'},cache:'no-store',signal});const t=await r.text();let d=null;try{d=JSON.parse(t)}catch{}if(!r.ok||d?.retCode!==0)throw new Error('Bybit '+path+' HTTP '+r.status+': '+(d?.retMsg||t.slice(0,300)));return d}
async function safe(label,path,params,signal){try{return{ok:true,label,value:await request(path,params,signal)}}catch(e){return{ok:false,label,error:e?.message||String(e)}}}
const audit=x=>{const a=Object.values(x);return{requested:a.length,successful:a.filter(v=>v.ok).length,failed:a.filter(v=>!v.ok).length,failures:a.filter(v=>!v.ok).map(v=>({label:v.label,error:v.error}))}};
const val=(x,k)=>x?.[k]?.ok?x[k].value:null;
function bookMetrics(b){const bids=(b?.b||[]).map(x=>[num(x[0]),num(x[1])]).filter(x=>x.every(Number.isFinite));const asks=(b?.a||[]).map(x=>[num(x[0]),num(x[1])]).filter(x=>x.every(Number.isFinite));const bn=bids.reduce((s,x)=>s+x[0]*x[1],0),an=asks.reduce((s,x)=>s+x[0]*x[1],0),bid=bids[0]?.[0]??null,ask=asks[0]?.[0]??null,mid=bid!=null&&ask!=null?(bid+ask)/2:null;return{bestBid:bid,bestAsk:ask,mid,spread:bid!=null&&ask!=null?ask-bid:null,spreadBps:mid?((ask-bid)/mid)*10000:null,bidNotional:bn,askNotional:an,imbalance:bn+an?(bn-an)/(bn+an):null,bids:bids.slice(0,200),asks:asks.slice(0,200)}}
function krows(rows,interval){const ms=interval==='D'?86400000:Number(interval)*60000;return(Array.isArray(rows)?rows:[]).map(x=>({time:num(x[0]),open:num(x[1]),high:num(x[2]),low:num(x[3]),close:num(x[4]),volume:num(x[5]),turnover:num(x[6]),confirmed:num(x[0])+ms<Date.now()})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)).reverse()}
async function batch(es,signal){const r=await Promise.all(es.map(e=>safe(e.label,e.path,e.params,signal)));return Object.fromEntries(r.map(x=>[x.label,x]))}
export async function getBybitFullMarketData({signal}={}){const c=new AbortController();const timer=setTimeout(()=>c.abort(),14000);try{const es=[
{label:'time',path:'/v5/market/time'},
{label:'linear.instruments',path:'/v5/market/instruments-info',params:{category:'linear',symbol:SYMBOL}},
{label:'spot.instruments',path:'/v5/market/instruments-info',params:{category:'spot',symbol:SYMBOL}},
{label:'linear.ticker',path:'/v5/market/tickers',params:{category:'linear',symbol:SYMBOL}},
{label:'spot.ticker',path:'/v5/market/tickers',params:{category:'spot',symbol:SYMBOL}},
{label:'linear.orderbook',path:'/v5/market/orderbook',params:{category:'linear',symbol:SYMBOL,limit:200}},
{label:'spot.orderbook',path:'/v5/market/orderbook',params:{category:'spot',symbol:SYMBOL,limit:200}},
{label:'linear.trades',path:'/v5/market/recent-trade',params:{category:'linear',symbol:SYMBOL,limit:1000}},
{label:'spot.trades',path:'/v5/market/recent-trade',params:{category:'spot',symbol:SYMBOL,limit:60}},
{label:'linear.deliveryPrice',path:'/v5/market/delivery-price',params:{category:'linear',symbol:SYMBOL,limit:200}},
{label:'linear.riskLimit',path:'/v5/market/risk-limit',params:{category:'linear',symbol:SYMBOL}},
{label:'linear.priceLimit',path:'/v5/market/price-limit',params:{category:'linear',symbol:SYMBOL}},
{label:'linear.funding',path:'/v5/market/funding/history',params:{category:'linear',symbol:SYMBOL,limit:200}},
{label:'linear.openInterest',path:'/v5/market/open-interest',params:{category:'linear',symbol:SYMBOL,intervalTime:'15min',limit:200}},
{label:'linear.longShort',path:'/v5/market/account-ratio',params:{category:'linear',symbol:SYMBOL,period:'15min',limit:200}}];
for(const i of INTERVALS){es.push({label:'linear.kline.'+i,path:'/v5/market/kline',params:{category:'linear',symbol:SYMBOL,interval:i,limit:1000}},{label:'spot.kline.'+i,path:'/v5/market/kline',params:{category:'spot',symbol:SYMBOL,interval:i,limit:1000}},{label:'linear.markKline.'+i,path:'/v5/market/mark-price-kline',params:{category:'linear',symbol:SYMBOL,interval:i,limit:1000}},{label:'linear.indexKline.'+i,path:'/v5/market/index-price-kline',params:{category:'linear',symbol:SYMBOL,interval:i,limit:1000}},{label:'linear.premiumKline.'+i,path:'/v5/market/premium-index-price-kline',params:{category:'linear',symbol:SYMBOL,interval:i,limit:1000}})}
for(const p of PERIODS){es.push({label:'linear.longShort.'+p,path:'/v5/market/account-ratio',params:{category:'linear',symbol:SYMBOL,period:p,limit:200}});if(['5min','15min','30min','1h','4h','1d'].includes(p))es.push({label:'linear.oi.'+p,path:'/v5/market/open-interest',params:{category:'linear',symbol:SYMBOL,intervalTime:p,limit:200}})}
const r=await batch(es,c.signal);const lt=val(r,'linear.ticker')?.result?.list?.[0]||{},st=val(r,'spot.ticker')?.result?.list?.[0]||{};const f={symbol:SYMBOL,audit:audit(r),ticker:lt,orderBook:{raw:val(r,'linear.orderbook')?.result,metrics:bookMetrics(val(r,'linear.orderbook')?.result)},trades:val(r,'linear.trades')?.result?.list||[],instruments:val(r,'linear.instruments')?.result||null,deliveryPrice:val(r,'linear.deliveryPrice')?.result?.list||[],riskLimit:val(r,'linear.riskLimit')?.result||null,priceLimit:val(r,'linear.priceLimit')?.result||null,fundingHistory:val(r,'linear.funding')?.result?.list||[],openInterest:val(r,'linear.openInterest')?.result?.list||[],longShort:val(r,'linear.longShort')?.result?.list||[],histories:{openInterest:{},longShort:{}},candles:{klines:{},markPrice:{},indexPrice:{},premiumIndex:{}}};
for(const i of INTERVALS){f.candles.klines[i]=krows(val(r,'linear.kline.'+i)?.result?.list||[],i);f.candles.markPrice[i]=krows(val(r,'linear.markKline.'+i)?.result?.list||[],i);f.candles.indexPrice[i]=krows(val(r,'linear.indexKline.'+i)?.result?.list||[],i);f.candles.premiumIndex[i]=krows(val(r,'linear.premiumKline.'+i)?.result?.list||[],i)}
for(const p of PERIODS){f.histories.openInterest[p]=val(r,'linear.oi.'+p)?.result?.list||[];f.histories.longShort[p]=val(r,'linear.longShort.'+p)?.result?.list||[]}
const s={symbol:SYMBOL,ticker:st,instruments:val(r,'spot.instruments')?.result||null,orderBook:{raw:val(r,'spot.orderbook')?.result,metrics:bookMetrics(val(r,'spot.orderbook')?.result)},trades:val(r,'spot.trades')?.result?.list||[],candles:{}};for(const i of INTERVALS)s.candles[i]=krows(val(r,'spot.kline.'+i)?.result?.list||[],i);
const q=audit(r);return{available:q.successful>0,source:'BYBIT',environment:BASE.includes('testnet')?'testnet':'production',symbol:SYMBOL,fetchedAt:new Date().toISOString(),coverage:{scope:'ETHUSDT Linear + Spot public market data',timeframes:INTERVALS,requestedEndpointCount:q.requested,successfulEndpointCount:q.successful,failedEndpointCount:q.failed,documentedV5MarketData:true},summary:{linearPrice:num(lt.lastPrice),markPrice:num(lt.markPrice),indexPrice:num(lt.indexPrice),fundingRate:num(lt.fundingRate),nextFundingTime:num(lt.nextFundingTime),openInterest:num(lt.openInterest),spotPrice:num(st.lastPrice),basis:num(lt.basis),basisRate:num(lt.basisRate),book:f.orderBook.metrics},futures:f,spot:s,quality:{live:true,audit:q,allRequestedEndpointsSucceeded:q.failed===0}}}finally{clearTimeout(timer)}}
export async function getBybitEthContext({signal}={}){const d=await getBybitFullMarketData({signal});return{configured:true,available:d.available,source:d.source,category:'linear',symbol:SYMBOL,fetchedAt:d.fetchedAt,ticker:{lastPrice:d.summary.linearPrice,markPrice:d.summary.markPrice,indexPrice:d.summary.indexPrice,volume24h:num(d.futures?.ticker?.volume24h),turnover24h:num(d.futures?.ticker?.turnover24h),fundingRate:d.summary.fundingRate,openInterest:d.summary.openInterest},orderBook:d.summary.book,funding:{fundingRate:d.summary.fundingRate,timestamp:null},openInterest:{value:d.summary.openInterest,timestamp:null},quality:d.quality,full:d}}