const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const mean=a=>{a=(a||[]).filter(Number.isFinite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:null};
const stdev=a=>{a=(a||[]).filter(Number.isFinite);if(a.length<2)return null;const m=mean(a);return Math.sqrt(mean(a.map(v=>(v-m)**2)))};
const clamp=(v,a=-1,b=1)=>Number.isFinite(v)?Math.max(a,Math.min(b,v)):0;
const sgn=v=>v>0?1:v<0?-1:0;
const dir=s=>s>.12?'BULLISH':s<-.12?'BEARISH':'NEUTRAL';
function ema(a,p){a=(a||[]).filter(Number.isFinite);if(a.length<p)return null;let e=mean(a.slice(0,p)),k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function sma(a,p){return (a||[]).length<p?null:mean(a.slice(-p))}
function atr(c,p=14){if(!c||c.length<=p)return null;const x=[];for(let i=1;i<c.length;i++){const q=c[i],r=c[i-1];x.push(Math.max(q.high-q.low,Math.abs(q.high-r.close),Math.abs(q.low-r.close)))}return mean(x.slice(-p))}
function rsi(c,p=14){if(!c||c.length<=p)return null;let g=0,l=0;for(let i=c.length-p;i<c.length;i++){const d=c[i].close-c[i-1].close;g+=Math.max(d,0);l+=Math.max(-d,0)}return l?100-100/(1+g/l):100}
function slope(a,n=20){a=(a||[]).filter(Number.isFinite).slice(-n);if(a.length<3)return 0;const mx=(a.length-1)/2,my=mean(a);let A=0,B=0;for(let i=0;i<a.length;i++){A+=(i-mx)*(a[i]-my);B+=(i-mx)**2}return B?A/B:0}
function pivots(c,l=3,r=3){const H=[],L=[];for(let i=l;i<c.length-r;i++){let h=1,lo=1;for(let j=1;j<=l;j++){h&&=c[i].high>c[i-j].high;lo&&=c[i].low<c[i-j].low}for(let j=1;j<=r;j++){h&&=c[i].high>=c[i+j].high;lo&&=c[i].low<=c[i+j].low}if(h)H.push({i,p:c[i].high,t:c[i].time});if(lo)L.push({i,p:c[i].low,t:c[i].time})}return{highs:H,lows:L}}
function liquidity(c,n=20){if(!c.length)return{};const x=c.at(-1),p=c.slice(-n-1,-1),hi=Math.max(...p.map(z=>z.high)),lo=Math.min(...p.map(z=>z.low)),a=atr(c)||1;return{hh:hi,ll:lo,sweepHigh:x.high>hi&&x.close<hi,sweepLow:x.low<lo&&x.close>lo,eqHigh:p.slice(-8).some(z=>Math.abs(z.high-hi)<=a*.15),eqLow:p.slice(-8).some(z=>Math.abs(z.low-lo)<=a*.15)}}
function fvg(c){if(c.length<3)return{};const a=c.at(-3),x=c.at(-1);return{bullish:x.low>a.high,bearish:x.high<a.low,bullGap:x.low>a.high?[a.high,x.low]:null,bearGap:x.high<a.low?[x.high,a.low]:null}}
function press(c){return c&&c.high>c.low?clamp((c.close-c.open)/(c.high-c.low)):0}
function volz(c,p=30){const v=c.at(-1)?.volume;return num(v)!=null&&stdev(c.slice(-p).map(x=>num(x.volume)))?clamp((v-mean(c.slice(-p).map(x=>x.volume)))/(stdev(c.slice(-p).map(x=>x.volume))||1)/4):0}
function delta(c,n=20){const x=c.slice(-n),d=x.reduce((s,z)=>s+press(z)*z.volume,0),v=x.reduce((s,z)=>s+z.volume,0);return v?d/v:0}
function eff(c,n=20){if(c.length<n)return 0;const x=c.slice(-n),p=x.slice(1).reduce((s,z,i)=>s+Math.abs(z.close-x[i].close),0),net=Math.abs(x.at(-1).close-x[0].close);return p?net/p:0}
function oi(ctx){const d=ctx.derivatives||{},h=(d.history?.oi||[]).map(x=>num(x.oi)).filter(Number.isFinite),f=(d.history?.funding||[]).map(x=>num(x.fundingRate)).filter(Number.isFinite),o=num(d.current?.openInterest?.oi),fr=num(d.current?.fundingRate);const z=(v,a)=>{const m=mean(a),q=stdev(a);return v!=null&&m!=null&&q?v-m? (v-m)/q:0:null};return{oi:o,fr,oiDelta:h.length>1?h.at(-1)-h.at(-2):0,oiZ:z(o,h),fundZ:z(fr,f),fundingMean:mean(f)}}
const N={
 '01':['Aggregated Open Interest','OPEN_INTEREST'],'02':['Coyote OI Suite [Aggregated]','OPEN_INTEREST'],'03':['Aggregated Open Interest [Alpha Extract]','OPEN_INTEREST'],'04':['Auto Harmonic Patterns [AFD]','PATTERN'],'05':['Auto Range Detector [QuantAlgo]','REGIME'],'06':['Buy/Sell Zones','VOLUME'],'07':['CandelaCharts Value Area Reversals','VALUE_AREA'],'08':['Classical Auto Chart Patterns [AFD]','PATTERN'],'09':['Contested Volume Bubbles','VOLUME'],'10':['Coppock Curve Multi-Filter','MOMENTUM'],'11':['CVD Divergence Insights','CVD'],'12':['Dual-Phase Reversal by DGT','REVERSAL'],'13':['Elliott Impulse Engine','STRUCTURE'],'14':['The Distilled Sweep Zone','LIQUIDITY'],'15':['MBF & RZ Liquidity Radar v0.6.6','LIQUIDITY'],'16':['Liquidity Sweep Hunter Algo','LIQUIDITY'],'17':['Market Path Forecast','FORECAST'],'18':['Merged Master Indicator','SMC'],'19':['MTF Liquidity Stack','LIQUIDITY'],'20':['Open Interest Suite','OPEN_INTEREST'],'21':['Aggregated OI Z-Score','OPEN_INTEREST'],'22':['Reversal Probability Profile','LEVEL_DENSITY'],'23':['Setup Scanner','SETUP'],'24':['LuxAlgo SMC','SMC'],'25':['SMC Confluence Suite','SMC'],'26':['STRAT Trap & VWAP Engine','SETUP'],'27':['Structure-Anchored VWAP','VWAP'],'28':['Liquidity Sweep Reversal Strategy','SETUP'],'29':['Distilled HTF PO3','EVENT_SEQUENCE'],'30':['Triple Supertrend Confluence','TREND'],'31':['Ultimate Order Flow, VWAP & Liquidation Heatmap','ORDER_FLOW_PROXY'],'32':['Uptrick Adaptive Trend Trail','REGIME'],'33':['Volume-Weighted Order Block Zones','ORDER_BLOCK'],'34':['WaveTrend Oscillator','OSCILLATOR'],'35':['Williams Variable A/D Pressure','PRESSURE']
};
export const INDICATOR_NAMES=Object.fromEntries(Object.entries(N).map(([id,v])=>[id,{name:v[0],category:v[1]}]));
export function computeIndicator(id,c,ctx={}){
 if(!c?.length)return{status:'NO_DATA',score:0,state:{status:'NO_DATA',direction:'NEUTRAL',strength:0},features:{},diagnostics:{warnings:['No confirmed candles'],errors:[]},parity:'SEMANTIC_PORT_V1'};
 const x=c.at(-1),p=c.at(-2)||x,a=atr(c)||1,r=rsi(c),v=volz(c),d=delta(c),e=eff(c),q=liquidity(c),g=fvg(c),w=sma(c.map(z=>z.volume),20)||x.volume,o=oi(ctx),vw=sma(c.map(z=>z.close),55)||x.close;let score=0,features={},warnings=[];
 switch(id){
 case '01':score=clamp(sgn(o.oiDelta)*.45+(o.oiZ||0)/5);features={oi:o.oi,oiDelta:o.oiDelta,oiZ:o.oiZ};break;
 case '02':score=clamp(sgn(o.fr)*.3+sgn(o.oiDelta)*.4+sgn((ctx.derivatives?.history?.longShort||[]).at(-1)?.longShortRatio-1)*.3);features={funding:o.fr,oiDelta:o.oiDelta,fundingZ:o.fundZ};break;
 case '03':{const pr=x.close/p.close-1;score=clamp(-sgn(pr)*sgn(o.oiDelta)*.8+sgn(pr)*.2);features={priceReturn:pr,oiDelta:o.oiDelta,divergence:sgn(pr)!==sgn(o.oiDelta)};break}
 case '04':{const z=pivots(c);score=clamp(sgn((z.highs.at(-1)?.p||x.high)-(z.highs.at(-2)?.p||x.high))*.5+sgn((z.lows.at(-1)?.p||x.low)-(z.lows.at(-2)?.p||x.low))*.5);features={pivotHighs:z.highs.slice(-3),pivotLows:z.lows.slice(-3),harmonicCandidate:z.highs.length>=3&&z.lows.length>=3};warnings.push('Geometry candidate; not pattern certainty.');break}
 case '05':score=clamp((adx(c)-20)/35*sgn(slope(c.map(z=>z.close))));features={adxProxy:adx(c),atr:a,efficiency:e};break;
 case '06':{const b=c.slice(-40).filter(z=>z.close>z.open).reduce((s,z)=>s+z.volume,0),s=c.slice(-40).filter(z=>z.close<z.open).reduce((u,z)=>u+z.volume,0);score=clamp((b-s)/(b+s||1));features={bullVolume:b,bearVolume:s};break}
 case '07':{const pos=clamp((x.close-vw)/(a*6),-1,1);score=-pos*.7+sgn((r||50)-50)*.3;features={vwap:vw,rangePosition:pos,rsi:r};break}
 case '08':{const hi=Math.max(...c.slice(-30).map(z=>z.high)),lo=Math.min(...c.slice(-30).map(z=>z.low));score=x.close>hi?1:x.close<lo?-1:clamp((x.close-(hi+lo)/2)/(a*6));features={rangeHigh:hi,rangeLow:lo};break}
 case '09':score=clamp(press(x)*.55+v*.45);features={volumeZ:v,pressure:press(x),contestIndex:1-Math.abs(x.close-x.open)/(x.high-x.low||1)};break;
 case '10':{const r10=c.length>10?x.close/c.at(-11).close-1:0,r14=c.length>14?x.close/c.at(-15).close-1:0;score=clamp((r10+r14)*20);features={roc10:r10,roc14:r14,coppock:r10+r14};break}
 case '11':{const pr=c.length>10?x.close/c.at(-11).close-1:0;score=clamp(d*2+sgn(pr)*.2);features={cvdProxy:d,priceReturn:pr};warnings.push('Historical CVD is a candle-pressure proxy without persisted tick tape.');break}
 case '12':{const ex=r<25?1:r>75?-1:0;score=clamp(ex*.7+sgn(v)*sgn(ex)*.3);features={rsi:r,volumeZ:v,exhaustion:ex};break}
 case '13':{const z=pivots(c,4,4),seq=[...z.highs.slice(-3),...z.lows.slice(-3)].sort((a,b)=>a.i-b.i);score=clamp(sgn((seq.at(-1)?.p||x.close)-(seq.at(-2)?.p||x.close)));features={pivotSequence:seq};warnings.push('Pivot-sequence proxy, not discretionary Elliott labeling.');break}
 case '14':score=q.sweepHigh?-1:q.sweepLow?1:0;features=q;break;
 case '15':score=clamp(((q.eqLow ? .25 : 0)||0)+(q.eqHigh?-.25:0)+((q.sweepLow ? .5 : 0))+((q.sweepHigh ? -.5 : 0)));features=q;break;
 case '16':{const sw=q.sweepHigh?-1:q.sweepLow?1:0,cf=sw<0?(x.close<p.close?-1:0):sw>0?(x.close>p.close?1:0):0;score=clamp(sw*.7+cf*.3);features={sweep:sw,confirmation:cf};break}
 case '17':{const rs=[];for(let i=Math.max(4,c.length-40);i<c.length;i++)rs.push(c[i].close/c[i-4].close-1);score=clamp((mean(rs)/(stdev(rs)||1))*.25);features={meanPathReturn:mean(rs),pathVolatility:stdev(rs)};warnings.push('Expectation envelope; not calibrated probability.');break}
 case '18':score=clamp(sgn(x.close-(ema(c.map(z=>z.close),16)||x.close))*.5+d*.5);features={hullProxy:ema(c.map(z=>z.close),16),deltaProxy:d,fvg:g};warnings.push('Confirmed-candle FVG semantics; no lookahead.');break;
 case '19':{const rows=Object.entries(ctx.candlesByTf||{}).map(([tf,z])=>{const l=liquidity(z||[]);return{tf,sweepHigh:l.sweepHigh,sweepLow:l.sweepLow}});score=clamp(mean(rows.map(z=>z.sweepLow?1:z.sweepHigh?-1:0))||0);features={stack:rows};break}
 case '20':score=clamp(sgn(o.oiDelta)*.6+sgn(o.fr)*.4);features={oi:o.oi,oiDelta:o.oiDelta,funding:o.fr};break;
 case '21':score=clamp((o.oiZ||0)/3);features={oi:o.oi,oiZ:o.oiZ,samples:o.h?.length||0};break;
 case '22':{const z=pivots(c),density=clamp((z.highs.length+z.lows.length)/Math.max(1,c.length/6),0,1);score=clamp((x.close-vw)/(a*5))*density;features={pivotCount:z.highs.length+z.lows.length,density,vwap:vw};warnings.push('Level density is not empirical reversal probability.');break}
 case '23':{const e20=ema(c.map(z=>z.close),20),reclaim=p.close<vw&&x.close>vw,pull=x.close>(e20||x.close)&&p.close<(ema(c.slice(0,-1).map(z=>z.close),20)||p.close);score=clamp(((reclaim ? .6 : 0)+(pull ? .35 : 0)+(q.sweepLow ? .4 : q.sweepHigh ? -.4 : 0)));features={vwapReclaim:reclaim,emaPullback:pull,sweepLow:q.sweepLow,sweepHigh:q.sweepHigh};break}
 case '24':score=clamp(sgn(x.close-(ema(c.map(z=>z.close),50)||x.close))*.45+(g.bullish ? .35 : g.bearish ? -.35 : 0)+d*.2);features={ema50:ema(c.map(z=>z.close),50),fvg:g};warnings.push('FVG is normalized to confirmed candles.');break;
 case '25':{const tr=sgn(slope(c.map(z=>z.close),30)),ls=q.sweepLow?1:q.sweepHigh?-1:0,gs=g.bullish?1:g.bearish?-1:0;score=clamp(tr*.35+sgn(adx(c)-20)*.2+ls*.2+gs*.25);features={trend:tr,adxProxy:adx(c),liquidity:ls,fvg:gs};break}
 case '26':{const trap=sgn(press(x))!==sgn(press(p))&&Math.abs(x.close-x.open)/(x.high-x.low||1)<.55?-sgn(press(x)):0;score=clamp(sgn(x.close-vw)*.4+trap*.6);features={pressure:press(x),trap,vwap:vw};break}
 case '27':{score=clamp((x.close-vw)/(a*5));features={anchoredVWAP:vw,distanceATR:(x.close-vw)/a,anchorPivot:(pivots(c,5,5).highs.at(-1)?.p||pivots(c,5,5).lows.at(-1)?.p||x.close)};break}
 case '28':{const sw=q.sweepHigh?-1:q.sweepLow?1:0,cf=sw<0?(x.close<p.close?-1:0):sw>0?(x.close>p.close?1:0):0;score=clamp(sw*.7+cf*.3);features={sweep:sw,confirmedReversal:cf,stopReference:sw<0?q.hh:sw>0?q.ll:null};break}
 case '29':{const sw=q.sweepHigh?-1:q.sweepLow?1:0,ds=sgn(press(x)),gs=g.bullish?1:g.bearish?-1:0;score=clamp(sw*.4+ds*.25+gs*.35);features={sweep:sw,displacement:ds,fvg:gs,sequenceComplete:sw!==0&&ds===sw};break}
 case '30':{const tr=sgn(x.close-(ema(c.map(z=>z.close),10)||x.close));score=clamp(tr*.65+sgn(adx(c)-18)*tr*.2+sgn(slope(c.map(z=>z.close)))*.15);features={trendProxy:tr,adxProxy:adx(c),persistence:sgn(slope(c.map(z=>z.close)))};break}
 case '31':{const ob=ctx.market?.orderBook||{},b=(ob.bids||[]).slice(0,100).reduce((s,z)=>s+Number(z.size??z[1]??0),0),ak=(ob.asks||[]).slice(0,100).reduce((s,z)=>s+Number(z.size??z[1]??0),0),im=(b+ak)?(b-ak)/(b+ak):0;score=clamp(d*.65+im*.35);features={lowerTFDeltaProxy:d,orderBookImbalance:im,bidDepth:b,askDepth:ak};warnings.push('Order-flow is a proxy unless aggressor-side tape is persisted.');break}
 case '32':{const tr=sgn(x.close-(ema(c.map(z=>z.close),20)||x.close)),mom=(r-50)/25;score=clamp(tr*.45+clamp(mom)*.25+(e-.35)*.3);features={efficiency:e,chop:1-e,trend:tr,momentum:mom,regime:e>.55?'TREND':e<.28?'CHOP':'TRANSITION'};break}
 case '33':{const z=pivots(c),ph=z.highs.at(-1)?.p,pl=z.lows.at(-1)?.p,rv=w?x.volume/w:1,sig=ph&&x.close>ph?1:pl&&x.close<pl?-1:0;score=clamp(sig*Math.min(rv,2)/2);features={lastPivotHigh:ph??null,lastPivotLow:pl??null,relativeVolume:rv};break}
 case '34':{const q1=ema(c.map(z=>(z.high+z.low+z.close)/3),10),q2=ema(c.map(z=>z.close),21);score=clamp(sgn((q1??x.close)-(q2??x.close)));features={waveTrendProxy:q1,q2};break}
 case '35':{const z=c.slice(-20).map(y=>y.high===y.low?0:(y.close-y.open)/(y.high-y.low)*y.volume),wv=mean(z),mu=mean(c.slice(-60).map(y=>y.high===y.low?0:(y.close-y.open)/(y.high-y.low)*y.volume));score=clamp(sgn(wv-mu)*.7+sgn((r||50)-50)*.3);features={wvad:wv,wvadBaseline:mu,rsi:r,adxProxy:adx(c)};break}
 }
 return{id,name:INDICATOR_NAMES[id].name,category:INDICATOR_NAMES[id].category,score:clamp(score),state:{status:'CALCULATED',direction:dir(clamp(score)),strength:Math.abs(clamp(score))},features,diagnostics:{warnings,errors:[]},parity:'SEMANTIC_PORT_V1'};
}
function adx(c,n=14){if(c.length<n+2)return 0;let tr=0,u=0,d=0;for(let i=c.length-n;i<c.length;i++){const x=c[i],p=c[i-1];tr+=Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close));const up=x.high-p.high,dn=p.low-x.low;u+=up>0&&up>dn?up:0;d+=dn>0&&dn>up?dn:0}const a=100*u/(tr||1),b=100*d/(tr||1);return 100*Math.abs(a-b)/((a+b)||1)}